export const ERROR_CODES = {
  SUCCESS: 0,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
}

export const ERROR_MESSAGES = {
  MISSING_PARAMS: "缺少必要参数",
  INVALID_PHONE: "请输入正确的手机号",
  PHONE_EXISTS: "该手机号已注册",
  PHONE_NOT_REGISTERED: "该手机号未注册",
  INVALID_CODE: "验证码无效或已过期",
  CODE_EXPIRED: "验证码已过期",
  INVALID_PASSWORD: "密码错误",
  PASSWORD_MISMATCH: "两次密码不一致",
  USER_NOT_FOUND: "用户不存在",
  USER_NOT_LOGIN: "请先登录",
  REGISTER_FAILED: "注册失败",
  LOGIN_FAILED: "登录失败",
  SEND_CODE_FAILED: "发送验证码失败",
  CREATE_MATCH_FAILED: "创建匹配失败",
  GET_MATCH_LIST_FAILED: "获取匹配列表失败",
  GET_USER_PROFILE_FAILED: "获取用户信息失败",
  UPDATE_USER_PROFILE_FAILED: "更新用户信息失败",
  INVALID_INVITE_CODE: "邀请码或联系电话错误，或商家未通过审核",
  UPLOAD_FAILED: "上传失败",
  NETWORK_ERROR: "网络错误，请稍后重试",
  UNKNOWN_ERROR: "未知错误",
}

export const API_ERRORS = {
  MISSING_PARAMS: {
    code: ERROR_CODES.BAD_REQUEST,
    message: ERROR_MESSAGES.MISSING_PARAMS,
  },
  INVALID_PHONE: {
    code: ERROR_CODES.BAD_REQUEST,
    message: ERROR_MESSAGES.INVALID_PHONE,
  },
  PHONE_EXISTS: {
    code: ERROR_CODES.BAD_REQUEST,
    message: ERROR_MESSAGES.PHONE_EXISTS,
  },
  PHONE_NOT_REGISTERED: {
    code: ERROR_CODES.BAD_REQUEST,
    message: ERROR_MESSAGES.PHONE_NOT_REGISTERED,
  },
  INVALID_CODE: {
    code: ERROR_CODES.BAD_REQUEST,
    message: ERROR_MESSAGES.INVALID_CODE,
  },
  USER_NOT_FOUND: {
    code: ERROR_CODES.NOT_FOUND,
    message: ERROR_MESSAGES.USER_NOT_FOUND,
  },
  USER_NOT_LOGIN: {
    code: ERROR_CODES.UNAUTHORIZED,
    message: ERROR_MESSAGES.USER_NOT_LOGIN,
  },
  INVALID_INVITE_CODE: {
    code: ERROR_CODES.UNAUTHORIZED,
    message: ERROR_MESSAGES.INVALID_INVITE_CODE,
  },
  INTERNAL_ERROR: {
    code: ERROR_CODES.INTERNAL_ERROR,
    message: ERROR_MESSAGES.UNKNOWN_ERROR,
  },
}
